/*
  Nombre del proyecto: Sistema Web de Gestion de Inventario Tecnologico para la FISEI
  Universidad Tecnica de Ambato
  Facultad: Facultad de Ingenieria en Sistemas, Electronica e Industrial
  Carrera: Software
  Asignatura: Base de Datos
  Descripcion: Modelo fisico Oracle, datos de prueba, consultas y verificacion para administrar inventario tecnologico, prestamos, mantenimientos, movimientos, notificaciones, imagenes y auditoria.
  Integrantes: Guatemal Avilez Bryan Stalin; Bejarano Masabanda Carlos Fabian; Molina Nunez Karen Valeria; Espin Caiza Camila Gisselle
  Fecha: 05 de mayo de 2026
*/

ALTER SESSION SET CURRENT_SCHEMA = GITT_INV;

PROMPT A. Encabezado del proyecto cargado.
PROMPT B-F. Limpieza, tablas, restricciones, indices, comentarios y triggers.
-- Modelo fisico Oracle - Sistema Web de Gestion de Inventario Tecnologico para la FISEI

BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_PRESTAMO_DEVOLUCION'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4080 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_DETALLE_PRESTAMO_VALIDAR'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4080 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_DETALLE_PRESTAMO_ESTADO'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4080 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_ARTICULO_AUDITORIA'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4080 THEN RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE AUDITORIA CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE NOTIFICACION CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE MOVIMIENTO CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE MANTENIMIENTO CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE DETALLE_PRESTAMO CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE IMAGEN_ARTICULO CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE PRESTAMO CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE ARTICULO CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CATEGORIA CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE UBICACION CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE DEPARTAMENTO CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE USUARIO CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE ROL CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/

CREATE TABLE ROL (
    id_rol NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 100) PRIMARY KEY,
    nombre_rol VARCHAR2(50) NOT NULL,
    CONSTRAINT uk_rol_nombre UNIQUE (nombre_rol)
);

CREATE TABLE USUARIO (
    id_usuario NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 100) PRIMARY KEY,
    nombre VARCHAR2(120) NOT NULL,
    correo VARCHAR2(150) NOT NULL,
    contrasena VARCHAR2(255) NOT NULL,
    id_rol NUMBER NOT NULL,
    fecha_creacion DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT fk_usuario_rol FOREIGN KEY (id_rol) REFERENCES ROL(id_rol)
);

CREATE TABLE DEPARTAMENTO (
    id_departamento NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 100) PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    CONSTRAINT uk_departamento_nombre UNIQUE (nombre)
);

CREATE TABLE UBICACION (
    id_ubicacion NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 100) PRIMARY KEY,
    nombre VARCHAR2(120) NOT NULL,
    id_departamento NUMBER NOT NULL,
    CONSTRAINT fk_ubicacion_departamento FOREIGN KEY (id_departamento) REFERENCES DEPARTAMENTO(id_departamento)
);

CREATE TABLE CATEGORIA (
    id_categoria NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 100) PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    CONSTRAINT uk_categoria_nombre UNIQUE (nombre)
);

CREATE TABLE ARTICULO (
    id_articulo NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 100) PRIMARY KEY,
    nombre VARCHAR2(120) NOT NULL,
    estado VARCHAR2(20) DEFAULT 'DISPONIBLE' NOT NULL,
    codigo VARCHAR2(50) NOT NULL,
    id_categoria NUMBER NOT NULL,
    id_ubicacion NUMBER NOT NULL,
    id_responsable NUMBER NULL,
    valor_estimado NUMBER(10,2) DEFAULT 0 NOT NULL,
    descripcion VARCHAR2(500),
    fecha_creacion DATE DEFAULT SYSDATE NOT NULL,
    fecha_actualizacion DATE,
    CONSTRAINT ck_articulo_estado CHECK (estado IN ('DISPONIBLE','PRESTADO','MANTENIMIENTO','BAJA')),
    CONSTRAINT fk_articulo_categoria FOREIGN KEY (id_categoria) REFERENCES CATEGORIA(id_categoria),
    CONSTRAINT fk_articulo_ubicacion FOREIGN KEY (id_ubicacion) REFERENCES UBICACION(id_ubicacion),
    CONSTRAINT fk_articulo_responsable FOREIGN KEY (id_responsable) REFERENCES USUARIO(id_usuario) ON DELETE SET NULL
);

CREATE TABLE IMAGEN_ARTICULO (
    id_imagen NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 100) PRIMARY KEY,
    id_articulo NUMBER NOT NULL,
    url_imagen VARCHAR2(500) NOT NULL,
    descripcion VARCHAR2(250),
    es_principal CHAR(1) DEFAULT 'S' NOT NULL,
    fecha_creacion DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT ck_imagen_articulo_principal CHECK (es_principal IN ('S','N')),
    CONSTRAINT fk_imagen_articulo FOREIGN KEY (id_articulo) REFERENCES ARTICULO(id_articulo) ON DELETE CASCADE
);

CREATE TABLE PRESTAMO (
    id_prestamo NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 100) PRIMARY KEY,
    fecha_prestamo DATE DEFAULT SYSDATE NOT NULL,
    fecha_devolucion DATE NOT NULL,
    id_usuario NUMBER NOT NULL,
    estado VARCHAR2(20) DEFAULT 'ACTIVO' NOT NULL,
    observacion VARCHAR2(500),
    CONSTRAINT ck_prestamo_estado CHECK (estado IN ('ACTIVO','DEVUELTO','VENCIDO')),
    CONSTRAINT fk_prestamo_usuario FOREIGN KEY (id_usuario) REFERENCES USUARIO(id_usuario)
);

CREATE TABLE DETALLE_PRESTAMO (
    id_detalle NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 100) PRIMARY KEY,
    id_prestamo NUMBER NOT NULL,
    id_articulo NUMBER NOT NULL,
    CONSTRAINT uk_detalle_prestamo_articulo UNIQUE (id_prestamo, id_articulo),
    CONSTRAINT fk_detalle_prestamo FOREIGN KEY (id_prestamo) REFERENCES PRESTAMO(id_prestamo) ON DELETE CASCADE,
    CONSTRAINT fk_detalle_articulo FOREIGN KEY (id_articulo) REFERENCES ARTICULO(id_articulo)
);

CREATE TABLE MANTENIMIENTO (
    id_mantenimiento NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 100) PRIMARY KEY,
    tipo VARCHAR2(20) NOT NULL,
    fecha DATE NOT NULL,
    id_articulo NUMBER NOT NULL,
    estado VARCHAR2(20) DEFAULT 'PENDIENTE' NOT NULL,
    observacion VARCHAR2(500),
    CONSTRAINT ck_mantenimiento_tipo CHECK (tipo IN ('PREVENTIVO','CORRECTIVO')),
    CONSTRAINT ck_mantenimiento_estado CHECK (estado IN ('PENDIENTE','EN_PROCESO','FINALIZADO')),
    CONSTRAINT fk_mantenimiento_articulo FOREIGN KEY (id_articulo) REFERENCES ARTICULO(id_articulo)
);

CREATE TABLE MOVIMIENTO (
    id_movimiento NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 100) PRIMARY KEY,
    fecha DATE DEFAULT SYSDATE NOT NULL,
    tipo VARCHAR2(20) NOT NULL,
    id_articulo NUMBER NOT NULL,
    observacion VARCHAR2(500),
    CONSTRAINT ck_movimiento_tipo CHECK (tipo IN ('INGRESO','TRASLADO','PRESTAMO','DEVOLUCION','MANTENIMIENTO')),
    CONSTRAINT fk_movimiento_articulo FOREIGN KEY (id_articulo) REFERENCES ARTICULO(id_articulo)
);

CREATE TABLE NOTIFICACION (
    id_notificacion NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 100) PRIMARY KEY,
    mensaje VARCHAR2(500) NOT NULL,
    estado VARCHAR2(20) DEFAULT 'PENDIENTE' NOT NULL,
    id_prestamo NUMBER NOT NULL,
    fecha_creacion DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT ck_notificacion_estado CHECK (estado IN ('PENDIENTE','ENVIADA','LEIDA')),
    CONSTRAINT fk_notificacion_prestamo FOREIGN KEY (id_prestamo) REFERENCES PRESTAMO(id_prestamo) ON DELETE CASCADE
);

CREATE TABLE AUDITORIA (
    id_auditoria NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 100) PRIMARY KEY,
    accion VARCHAR2(20) NOT NULL,
    fecha DATE DEFAULT SYSDATE NOT NULL,
    id_usuario NUMBER NOT NULL,
    tabla VARCHAR2(50),
    descripcion VARCHAR2(500),
    CONSTRAINT ck_auditoria_accion CHECK (accion IN ('INSERT','UPDATE','DELETE','LOGIN','PRESTAMO','DEVOLUCION')),
    CONSTRAINT fk_auditoria_usuario FOREIGN KEY (id_usuario) REFERENCES USUARIO(id_usuario)
);

CREATE UNIQUE INDEX ix_usuario_correo ON USUARIO(correo);
ALTER TABLE USUARIO ADD CONSTRAINT uk_usuario_correo UNIQUE (correo) USING INDEX ix_usuario_correo;
CREATE UNIQUE INDEX ix_articulo_codigo ON ARTICULO(codigo);
ALTER TABLE ARTICULO ADD CONSTRAINT uk_articulo_codigo UNIQUE (codigo) USING INDEX ix_articulo_codigo;
CREATE INDEX ix_articulo_estado ON ARTICULO(estado);
CREATE INDEX ix_prestamo_fecha_prestamo ON PRESTAMO(fecha_prestamo);
CREATE INDEX ix_prestamo_fecha_devolucion ON PRESTAMO(fecha_devolucion);
CREATE INDEX ix_mantenimiento_fecha ON MANTENIMIENTO(fecha);
CREATE INDEX ix_ubicacion_departamento ON UBICACION(id_departamento);
CREATE INDEX ix_articulo_categoria ON ARTICULO(id_categoria);
CREATE INDEX ix_articulo_ubicacion ON ARTICULO(id_ubicacion);
CREATE INDEX ix_imagen_articulo ON IMAGEN_ARTICULO(id_articulo);

COMMENT ON TABLE ROL IS 'Catalogo de roles de usuario del sistema.';
COMMENT ON TABLE USUARIO IS 'Usuarios autenticados y responsables de prestamos o auditoria.';
COMMENT ON TABLE DEPARTAMENTO IS 'Departamentos de la FISEI.';
COMMENT ON TABLE UBICACION IS 'Ubicaciones fisicas pertenecientes a departamentos.';
COMMENT ON TABLE CATEGORIA IS 'Categorias de articulos tecnologicos.';
COMMENT ON TABLE ARTICULO IS 'Inventario tecnologico administrado por la FISEI.';
COMMENT ON TABLE IMAGEN_ARTICULO IS 'Imagenes o evidencias visuales asociadas a articulos.';
COMMENT ON TABLE PRESTAMO IS 'Cabecera de prestamos de articulos.';
COMMENT ON TABLE DETALLE_PRESTAMO IS 'Articulos incluidos en cada prestamo.';
COMMENT ON TABLE MANTENIMIENTO IS 'Historial y programacion de mantenimientos.';
COMMENT ON TABLE MOVIMIENTO IS 'Movimientos operativos de articulos.';
COMMENT ON TABLE NOTIFICACION IS 'Notificaciones asociadas a prestamos.';
COMMENT ON TABLE AUDITORIA IS 'Registro de acciones criticas del sistema.';

COMMENT ON COLUMN ROL.id_rol IS 'Clave primaria del rol.';
COMMENT ON COLUMN ROL.nombre_rol IS 'Nombre unico del rol.';
COMMENT ON COLUMN USUARIO.id_usuario IS 'Clave primaria del usuario.';
COMMENT ON COLUMN USUARIO.nombre IS 'Nombre completo del usuario.';
COMMENT ON COLUMN USUARIO.correo IS 'Correo unico usado para login.';
COMMENT ON COLUMN USUARIO.contrasena IS 'Contrasena de usuario para ambiente academico.';
COMMENT ON COLUMN USUARIO.id_rol IS 'Rol asignado al usuario.';
COMMENT ON COLUMN USUARIO.fecha_creacion IS 'Fecha de creacion del usuario.';
COMMENT ON COLUMN DEPARTAMENTO.id_departamento IS 'Clave primaria del departamento.';
COMMENT ON COLUMN DEPARTAMENTO.nombre IS 'Nombre del departamento.';
COMMENT ON COLUMN UBICACION.id_ubicacion IS 'Clave primaria de la ubicacion.';
COMMENT ON COLUMN UBICACION.nombre IS 'Nombre de la ubicacion fisica.';
COMMENT ON COLUMN UBICACION.id_departamento IS 'Departamento al que pertenece la ubicacion.';
COMMENT ON COLUMN CATEGORIA.id_categoria IS 'Clave primaria de la categoria.';
COMMENT ON COLUMN CATEGORIA.nombre IS 'Nombre de la categoria del articulo.';
COMMENT ON COLUMN ARTICULO.id_articulo IS 'Clave primaria del articulo.';
COMMENT ON COLUMN ARTICULO.nombre IS 'Nombre descriptivo del articulo.';
COMMENT ON COLUMN ARTICULO.estado IS 'Estado controlado por CHECK: DISPONIBLE, PRESTADO, MANTENIMIENTO o BAJA.';
COMMENT ON COLUMN ARTICULO.codigo IS 'Codigo institucional unico del articulo.';
COMMENT ON COLUMN ARTICULO.id_categoria IS 'Categoria asignada al articulo.';
COMMENT ON COLUMN ARTICULO.id_ubicacion IS 'Ubicacion actual del articulo.';
COMMENT ON COLUMN ARTICULO.id_responsable IS 'Usuario responsable opcional del articulo.';
COMMENT ON COLUMN ARTICULO.valor_estimado IS 'Valor economico estimado del articulo para reportes.';
COMMENT ON COLUMN ARTICULO.descripcion IS 'Descripcion tecnica u observacion del articulo.';
COMMENT ON COLUMN ARTICULO.fecha_creacion IS 'Fecha de registro del articulo.';
COMMENT ON COLUMN ARTICULO.fecha_actualizacion IS 'Ultima fecha de actualizacion del articulo.';
COMMENT ON COLUMN IMAGEN_ARTICULO.id_imagen IS 'Clave primaria de la imagen del articulo.';
COMMENT ON COLUMN IMAGEN_ARTICULO.id_articulo IS 'Articulo asociado a la imagen.';
COMMENT ON COLUMN IMAGEN_ARTICULO.url_imagen IS 'URL o ruta de la imagen del articulo.';
COMMENT ON COLUMN IMAGEN_ARTICULO.descripcion IS 'Descripcion de la imagen.';
COMMENT ON COLUMN IMAGEN_ARTICULO.es_principal IS 'Indica si la imagen es principal: S o N.';
COMMENT ON COLUMN IMAGEN_ARTICULO.fecha_creacion IS 'Fecha de registro de la imagen.';
COMMENT ON COLUMN PRESTAMO.id_prestamo IS 'Clave primaria del prestamo.';
COMMENT ON COLUMN PRESTAMO.fecha_prestamo IS 'Fecha de registro del prestamo.';
COMMENT ON COLUMN PRESTAMO.fecha_devolucion IS 'Fecha planificada o efectiva de devolucion.';
COMMENT ON COLUMN PRESTAMO.id_usuario IS 'Usuario que solicita el prestamo.';
COMMENT ON COLUMN PRESTAMO.estado IS 'Estado operacional del prestamo.';
COMMENT ON COLUMN PRESTAMO.observacion IS 'Observacion del prestamo.';
COMMENT ON COLUMN DETALLE_PRESTAMO.id_detalle IS 'Clave primaria del detalle de prestamo.';
COMMENT ON COLUMN DETALLE_PRESTAMO.id_prestamo IS 'Prestamo al que pertenece el detalle.';
COMMENT ON COLUMN DETALLE_PRESTAMO.id_articulo IS 'Articulo incluido en el prestamo.';
COMMENT ON COLUMN MANTENIMIENTO.id_mantenimiento IS 'Clave primaria del mantenimiento.';
COMMENT ON COLUMN MANTENIMIENTO.tipo IS 'Tipo de mantenimiento: PREVENTIVO o CORRECTIVO.';
COMMENT ON COLUMN MANTENIMIENTO.fecha IS 'Fecha del mantenimiento.';
COMMENT ON COLUMN MANTENIMIENTO.id_articulo IS 'Articulo mantenido.';
COMMENT ON COLUMN MANTENIMIENTO.estado IS 'Estado operativo del mantenimiento.';
COMMENT ON COLUMN MANTENIMIENTO.observacion IS 'Detalle del mantenimiento.';
COMMENT ON COLUMN MOVIMIENTO.id_movimiento IS 'Clave primaria del movimiento.';
COMMENT ON COLUMN MOVIMIENTO.fecha IS 'Fecha del movimiento.';
COMMENT ON COLUMN MOVIMIENTO.tipo IS 'Tipo de movimiento controlado por CHECK.';
COMMENT ON COLUMN MOVIMIENTO.id_articulo IS 'Articulo asociado al movimiento.';
COMMENT ON COLUMN MOVIMIENTO.observacion IS 'Observacion del movimiento.';
COMMENT ON COLUMN NOTIFICACION.id_notificacion IS 'Clave primaria de la notificacion.';
COMMENT ON COLUMN NOTIFICACION.mensaje IS 'Mensaje de la notificacion.';
COMMENT ON COLUMN NOTIFICACION.estado IS 'Estado de envio o lectura de la notificacion.';
COMMENT ON COLUMN NOTIFICACION.id_prestamo IS 'Prestamo asociado a la notificacion.';
COMMENT ON COLUMN NOTIFICACION.fecha_creacion IS 'Fecha de creacion de la notificacion.';
COMMENT ON COLUMN AUDITORIA.id_auditoria IS 'Clave primaria de auditoria.';
COMMENT ON COLUMN AUDITORIA.accion IS 'Accion critica registrada.';
COMMENT ON COLUMN AUDITORIA.fecha IS 'Fecha de la accion auditada.';
COMMENT ON COLUMN AUDITORIA.id_usuario IS 'Usuario asociado a la accion.';
COMMENT ON COLUMN AUDITORIA.tabla IS 'Tabla afectada por la accion.';
COMMENT ON COLUMN AUDITORIA.descripcion IS 'Descripcion de la accion auditada.';

CREATE OR REPLACE TRIGGER trg_articulo_auditoria
AFTER INSERT OR UPDATE OR DELETE ON ARTICULO
FOR EACH ROW
DECLARE
    v_usuario NUMBER;
    v_accion VARCHAR2(20);
    v_codigo VARCHAR2(50);
BEGIN
    IF INSERTING THEN
        v_accion := 'INSERT';
        v_usuario := NVL(:NEW.id_responsable, 1);
        v_codigo := :NEW.codigo;
    ELSIF UPDATING THEN
        v_accion := 'UPDATE';
        v_usuario := NVL(:NEW.id_responsable, NVL(:OLD.id_responsable, 1));
        v_codigo := :NEW.codigo;
    ELSE
        v_accion := 'DELETE';
        v_usuario := NVL(:OLD.id_responsable, 1);
        v_codigo := :OLD.codigo;
    END IF;

    INSERT INTO AUDITORIA (accion, fecha, id_usuario, tabla, descripcion)
    VALUES (
        v_accion,
        SYSDATE,
        v_usuario,
        'ARTICULO',
        'Auditoria automatica del articulo ' || v_codigo
    );
END;
/

CREATE OR REPLACE TRIGGER trg_detalle_prestamo_estado
AFTER INSERT OR UPDATE OF id_articulo ON DETALLE_PRESTAMO
FOR EACH ROW
DECLARE
    v_estado_prestamo PRESTAMO.estado%TYPE;
BEGIN
    SELECT estado INTO v_estado_prestamo FROM PRESTAMO WHERE id_prestamo = :NEW.id_prestamo;
    IF v_estado_prestamo = 'ACTIVO' THEN
        UPDATE ARTICULO SET estado = 'PRESTADO', fecha_actualizacion = SYSDATE WHERE id_articulo = :NEW.id_articulo;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_detalle_prestamo_validar
FOR INSERT OR UPDATE OF id_articulo, id_prestamo ON DETALLE_PRESTAMO
COMPOUND TRIGGER
    TYPE t_articulos IS TABLE OF NUMBER INDEX BY PLS_INTEGER;
    g_articulos t_articulos;
    g_count PLS_INTEGER := 0;
AFTER EACH ROW IS
BEGIN
    g_count := g_count + 1;
    g_articulos(g_count) := :NEW.id_articulo;
END AFTER EACH ROW;
AFTER STATEMENT IS
    v_total NUMBER;
BEGIN
    FOR i IN 1 .. g_count LOOP
        SELECT COUNT(*)
        INTO v_total
        FROM DETALLE_PRESTAMO dp
        JOIN PRESTAMO p ON p.id_prestamo = dp.id_prestamo
        WHERE dp.id_articulo = g_articulos(i)
          AND p.estado = 'ACTIVO';

        IF v_total > 1 THEN
            RAISE_APPLICATION_ERROR(-20001, 'El articulo ya se encuentra en un prestamo activo.');
        END IF;
    END LOOP;
END AFTER STATEMENT;
END;
/

CREATE OR REPLACE TRIGGER trg_prestamo_devolucion
AFTER UPDATE OF estado ON PRESTAMO
FOR EACH ROW
WHEN (NEW.estado = 'DEVUELTO' AND OLD.estado <> 'DEVUELTO')
BEGIN
    FOR r IN (SELECT id_articulo FROM DETALLE_PRESTAMO WHERE id_prestamo = :NEW.id_prestamo) LOOP
        UPDATE ARTICULO SET estado = 'DISPONIBLE', fecha_actualizacion = SYSDATE WHERE id_articulo = r.id_articulo;
        INSERT INTO MOVIMIENTO (fecha, tipo, id_articulo, observacion)
        VALUES (SYSDATE, 'DEVOLUCION', r.id_articulo, 'Devolucion registrada por trigger');
    END LOOP;

    INSERT INTO AUDITORIA (accion, fecha, id_usuario, tabla, descripcion)
    VALUES ('DEVOLUCION', SYSDATE, :NEW.id_usuario, 'PRESTAMO', 'Devolucion del prestamo ' || :NEW.id_prestamo);
END;
/


PROMPT H. Datos de prueba.
-- Datos de prueba para Oracle

INSERT INTO ROL (id_rol, nombre_rol) VALUES (1, 'Administrador');
INSERT INTO ROL (id_rol, nombre_rol) VALUES (2, 'Responsable');
INSERT INTO ROL (id_rol, nombre_rol) VALUES (3, 'Docente');
INSERT INTO ROL (id_rol, nombre_rol) VALUES (4, 'Estudiante');

INSERT INTO USUARIO (id_usuario, nombre, correo, contrasena, id_rol) VALUES (1, 'Administrador FISEI', 'admin@fisei.edu.ec', 'Admin123*', 1);
INSERT INTO USUARIO (id_usuario, nombre, correo, contrasena, id_rol) VALUES (2, 'Responsable Laboratorio', 'responsable@fisei.edu.ec', 'Resp123*', 2);
INSERT INTO USUARIO (id_usuario, nombre, correo, contrasena, id_rol) VALUES (3, 'Docente Sistemas', 'docente@fisei.edu.ec', 'Docente123*', 3);
INSERT INTO USUARIO (id_usuario, nombre, correo, contrasena, id_rol) VALUES (4, 'Estudiante Software', 'estudiante@fisei.edu.ec', 'Estudiante123*', 4);

INSERT INTO DEPARTAMENTO (id_departamento, nombre) VALUES (1, 'Laboratorios FISEI');
INSERT INTO DEPARTAMENTO (id_departamento, nombre) VALUES (2, 'Aulas');
INSERT INTO DEPARTAMENTO (id_departamento, nombre) VALUES (3, 'Administracion');

INSERT INTO UBICACION (id_ubicacion, nombre, id_departamento) VALUES (1, 'Laboratorio 1', 1);
INSERT INTO UBICACION (id_ubicacion, nombre, id_departamento) VALUES (2, 'Laboratorio 2', 1);
INSERT INTO UBICACION (id_ubicacion, nombre, id_departamento) VALUES (3, 'Aula 401', 2);
INSERT INTO UBICACION (id_ubicacion, nombre, id_departamento) VALUES (4, 'Bodega Tecnologica', 3);

INSERT INTO CATEGORIA (id_categoria, nombre) VALUES (1, 'Computadores');
INSERT INTO CATEGORIA (id_categoria, nombre) VALUES (2, 'Proyectores');
INSERT INTO CATEGORIA (id_categoria, nombre) VALUES (3, 'Redes');
INSERT INTO CATEGORIA (id_categoria, nombre) VALUES (4, 'Impresion');
INSERT INTO CATEGORIA (id_categoria, nombre) VALUES (5, 'Audio y Video');

INSERT INTO ARTICULO (id_articulo, nombre, estado, codigo, id_categoria, id_ubicacion, id_responsable, valor_estimado, descripcion) VALUES (1, 'Laptop Dell Latitude', 'DISPONIBLE', 'FISEI-LAP-001', 1, 1, 2, 950.00, 'Equipo portatil para docencia.');
INSERT INTO ARTICULO (id_articulo, nombre, estado, codigo, id_categoria, id_ubicacion, id_responsable, valor_estimado, descripcion) VALUES (2, 'Proyector Epson X49', 'DISPONIBLE', 'FISEI-PRO-001', 2, 3, 2, 680.00, 'Proyector para aulas.');
INSERT INTO ARTICULO (id_articulo, nombre, estado, codigo, id_categoria, id_ubicacion, id_responsable, valor_estimado, descripcion) VALUES (3, 'Switch Cisco 24P', 'DISPONIBLE', 'FISEI-RED-001', 3, 2, 2, 420.00, 'Switch de laboratorio.');
INSERT INTO ARTICULO (id_articulo, nombre, estado, codigo, id_categoria, id_ubicacion, id_responsable, valor_estimado, descripcion) VALUES (4, 'Impresora HP LaserJet', 'MANTENIMIENTO', 'FISEI-IMP-001', 4, 4, 2, 540.00, 'Impresora en revision.');
INSERT INTO ARTICULO (id_articulo, nombre, estado, codigo, id_categoria, id_ubicacion, id_responsable, valor_estimado, descripcion) VALUES (5, 'Tablet Android', 'BAJA', 'FISEI-TAB-001', 1, 4, NULL, 300.00, 'Equipo dado de baja.');
INSERT INTO ARTICULO (id_articulo, nombre, estado, codigo, id_categoria, id_ubicacion, id_responsable, valor_estimado, descripcion) VALUES (6, 'Camara Logitech', 'DISPONIBLE', 'FISEI-VID-001', 5, 1, 2, 180.00, 'Camara para videoconferencia.');

INSERT INTO IMAGEN_ARTICULO (id_imagen, id_articulo, url_imagen, descripcion, es_principal) VALUES (1, 1, 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853', 'Imagen referencial de laptop', 'S');
INSERT INTO IMAGEN_ARTICULO (id_imagen, id_articulo, url_imagen, descripcion, es_principal) VALUES (2, 2, 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3', 'Imagen referencial de proyector', 'S');
INSERT INTO IMAGEN_ARTICULO (id_imagen, id_articulo, url_imagen, descripcion, es_principal) VALUES (3, 3, 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31', 'Imagen referencial de equipos de red', 'S');

INSERT INTO PRESTAMO (id_prestamo, fecha_prestamo, fecha_devolucion, id_usuario, estado, observacion) VALUES (1, SYSDATE - 1, SYSDATE + 5, 3, 'ACTIVO', 'Prestamo para clase practica.');
INSERT INTO PRESTAMO (id_prestamo, fecha_prestamo, fecha_devolucion, id_usuario, estado, observacion) VALUES (2, SYSDATE - 10, SYSDATE - 2, 4, 'DEVUELTO', 'Prestamo finalizado.');
INSERT INTO PRESTAMO (id_prestamo, fecha_prestamo, fecha_devolucion, id_usuario, estado, observacion) VALUES (3, SYSDATE - 7, SYSDATE - 1, 3, 'ACTIVO', 'Prestamo vencido pendiente de devolucion.');

INSERT INTO DETALLE_PRESTAMO (id_detalle, id_prestamo, id_articulo) VALUES (1, 1, 1);
INSERT INTO DETALLE_PRESTAMO (id_detalle, id_prestamo, id_articulo) VALUES (2, 1, 2);
INSERT INTO DETALLE_PRESTAMO (id_detalle, id_prestamo, id_articulo) VALUES (3, 2, 3);
INSERT INTO DETALLE_PRESTAMO (id_detalle, id_prestamo, id_articulo) VALUES (4, 3, 6);

INSERT INTO MANTENIMIENTO (id_mantenimiento, tipo, fecha, id_articulo, estado, observacion) VALUES (1, 'PREVENTIVO', SYSDATE + 3, 4, 'PENDIENTE', 'Revision de toner y fusor.');
INSERT INTO MANTENIMIENTO (id_mantenimiento, tipo, fecha, id_articulo, estado, observacion) VALUES (2, 'CORRECTIVO', SYSDATE - 4, 3, 'FINALIZADO', 'Cambio de fuente de poder.');

INSERT INTO MOVIMIENTO (id_movimiento, fecha, tipo, id_articulo, observacion) VALUES (1, SYSDATE - 30, 'INGRESO', 1, 'Ingreso inicial al inventario.');
INSERT INTO MOVIMIENTO (id_movimiento, fecha, tipo, id_articulo, observacion) VALUES (2, SYSDATE - 29, 'INGRESO', 2, 'Ingreso inicial al inventario.');
INSERT INTO MOVIMIENTO (id_movimiento, fecha, tipo, id_articulo, observacion) VALUES (3, SYSDATE - 1, 'PRESTAMO', 1, 'Prestamo registrado.');
INSERT INTO MOVIMIENTO (id_movimiento, fecha, tipo, id_articulo, observacion) VALUES (4, SYSDATE - 1, 'PRESTAMO', 2, 'Prestamo registrado.');
INSERT INTO MOVIMIENTO (id_movimiento, fecha, tipo, id_articulo, observacion) VALUES (5, SYSDATE - 4, 'MANTENIMIENTO', 4, 'Articulo enviado a mantenimiento.');
INSERT INTO MOVIMIENTO (id_movimiento, fecha, tipo, id_articulo, observacion) VALUES (6, SYSDATE - 7, 'PRESTAMO', 6, 'Prestamo vencido.');

INSERT INTO NOTIFICACION (id_notificacion, mensaje, estado, id_prestamo) VALUES (1, 'Prestamo 1 proximo a devolucion.', 'PENDIENTE', 1);
INSERT INTO NOTIFICACION (id_notificacion, mensaje, estado, id_prestamo) VALUES (2, 'Prestamo 3 vencido.', 'ENVIADA', 3);
INSERT INTO NOTIFICACION (id_notificacion, mensaje, estado, id_prestamo) VALUES (3, 'Prestamo 2 fue devuelto.', 'LEIDA', 2);

INSERT INTO AUDITORIA (id_auditoria, accion, fecha, id_usuario, tabla, descripcion) VALUES (1, 'LOGIN', SYSDATE - 2, 1, 'USUARIO', 'Ingreso administrativo.');
INSERT INTO AUDITORIA (id_auditoria, accion, fecha, id_usuario, tabla, descripcion) VALUES (2, 'PRESTAMO', SYSDATE - 1, 3, 'PRESTAMO', 'Registro de prestamo 1.');
INSERT INTO AUDITORIA (id_auditoria, accion, fecha, id_usuario, tabla, descripcion) VALUES (3, 'DEVOLUCION', SYSDATE - 2, 4, 'PRESTAMO', 'Devolucion del prestamo 2.');

COMMIT;

PROMPT I. Consultas DQL.
-- Q1. Listar articulos disponibles con ubicacion y responsable.
SELECT a.id_articulo, a.codigo, a.nombre, u.nombre AS ubicacion, d.nombre AS departamento, r.nombre AS responsable
FROM ARTICULO a
JOIN UBICACION u ON u.id_ubicacion = a.id_ubicacion
JOIN DEPARTAMENTO d ON d.id_departamento = u.id_departamento
LEFT JOIN USUARIO r ON r.id_usuario = a.id_responsable
WHERE a.estado = 'DISPONIBLE'
ORDER BY a.nombre;

-- Q2. Obtener total de articulos por categoria.
SELECT c.nombre AS categoria, COUNT(a.id_articulo) AS total_articulos
FROM CATEGORIA c
LEFT JOIN ARTICULO a ON a.id_categoria = c.id_categoria
GROUP BY c.nombre
ORDER BY c.nombre;

-- Q3. Mostrar prestamos activos y fecha de devolucion.
SELECT p.id_prestamo, u.nombre AS usuario, p.fecha_prestamo, p.fecha_devolucion, p.estado
FROM PRESTAMO p
JOIN USUARIO u ON u.id_usuario = p.id_usuario
WHERE p.estado = 'ACTIVO'
ORDER BY p.fecha_devolucion;

-- Q4. Mostrar articulos con mantenimiento pendiente.
SELECT a.codigo, a.nombre AS articulo, m.tipo, m.fecha, m.estado, m.observacion
FROM MANTENIMIENTO m
JOIN ARTICULO a ON a.id_articulo = m.id_articulo
WHERE m.estado = 'PENDIENTE'
ORDER BY m.fecha;

-- Q5. Mostrar movimientos por articulo.
SELECT a.codigo, a.nombre AS articulo, mo.fecha, mo.tipo, mo.observacion
FROM MOVIMIENTO mo
JOIN ARTICULO a ON a.id_articulo = mo.id_articulo
ORDER BY a.codigo, mo.fecha DESC;

-- Q6. Mostrar notificaciones por prestamo.
SELECT p.id_prestamo, n.mensaje, n.estado, n.fecha_creacion
FROM NOTIFICACION n
JOIN PRESTAMO p ON p.id_prestamo = n.id_prestamo
ORDER BY p.id_prestamo, n.fecha_creacion DESC;

-- Q7. Mostrar auditoria por usuario.
SELECT u.nombre AS usuario, au.accion, au.fecha, au.tabla, au.descripcion
FROM AUDITORIA au
JOIN USUARIO u ON u.id_usuario = au.id_usuario
ORDER BY au.fecha DESC;

-- Q8. Mostrar articulos por departamento.
SELECT d.nombre AS departamento, a.codigo, a.nombre AS articulo, a.estado
FROM ARTICULO a
JOIN UBICACION u ON u.id_ubicacion = a.id_ubicacion
JOIN DEPARTAMENTO d ON d.id_departamento = u.id_departamento
ORDER BY d.nombre, a.nombre;

-- Q9. Mostrar historial completo de un prestamo.
SELECT p.id_prestamo, us.nombre AS usuario, a.codigo, a.nombre AS articulo, p.fecha_prestamo, p.fecha_devolucion, p.estado AS estado_prestamo, a.estado AS estado_articulo
FROM PRESTAMO p
JOIN USUARIO us ON us.id_usuario = p.id_usuario
JOIN DETALLE_PRESTAMO dp ON dp.id_prestamo = p.id_prestamo
JOIN ARTICULO a ON a.id_articulo = dp.id_articulo
ORDER BY p.id_prestamo, a.codigo;

-- Q10. Mostrar articulos prestados actualmente.
SELECT a.codigo, a.nombre AS articulo, p.id_prestamo, u.nombre AS usuario, p.fecha_devolucion
FROM ARTICULO a
JOIN DETALLE_PRESTAMO dp ON dp.id_articulo = a.id_articulo
JOIN PRESTAMO p ON p.id_prestamo = dp.id_prestamo
JOIN USUARIO u ON u.id_usuario = p.id_usuario
WHERE p.estado = 'ACTIVO'
ORDER BY p.fecha_devolucion;

-- Q11. Mostrar usuarios por rol.
SELECT r.nombre_rol, u.nombre, u.correo
FROM ROL r
LEFT JOIN USUARIO u ON u.id_rol = r.id_rol
ORDER BY r.nombre_rol, u.nombre;

-- Q12. Mostrar prestamos vencidos.
SELECT p.id_prestamo, u.nombre AS usuario, p.fecha_prestamo, p.fecha_devolucion, p.estado
FROM PRESTAMO p
JOIN USUARIO u ON u.id_usuario = p.id_usuario
WHERE p.estado = 'ACTIVO'
  AND p.fecha_devolucion < TRUNC(SYSDATE)
ORDER BY p.fecha_devolucion;

-- Q13. Calcular el valor total del inventario por departamento.
SELECT d.nombre AS departamento, COUNT(a.id_articulo) AS total_articulos, SUM(a.valor_estimado) AS valor_total
FROM DEPARTAMENTO d
JOIN UBICACION u ON u.id_departamento = d.id_departamento
JOIN ARTICULO a ON a.id_ubicacion = u.id_ubicacion
GROUP BY d.nombre
ORDER BY valor_total DESC;

-- Q14. Listar movimientos realizados por rango de fechas.
SELECT mo.id_movimiento, a.codigo, a.nombre AS articulo, mo.fecha, mo.tipo, mo.observacion
FROM MOVIMIENTO mo
JOIN ARTICULO a ON a.id_articulo = mo.id_articulo
WHERE mo.fecha BETWEEN TRUNC(SYSDATE) - 30 AND TRUNC(SYSDATE) + 1
ORDER BY mo.fecha DESC, a.codigo;


-- J. Verificacion final
SELECT 'ROL' AS tabla, COUNT(*) AS total FROM ROL
UNION ALL SELECT 'USUARIO', COUNT(*) FROM USUARIO
UNION ALL SELECT 'DEPARTAMENTO', COUNT(*) FROM DEPARTAMENTO
UNION ALL SELECT 'UBICACION', COUNT(*) FROM UBICACION
UNION ALL SELECT 'CATEGORIA', COUNT(*) FROM CATEGORIA
UNION ALL SELECT 'ARTICULO', COUNT(*) FROM ARTICULO
UNION ALL SELECT 'IMAGEN_ARTICULO', COUNT(*) FROM IMAGEN_ARTICULO
UNION ALL SELECT 'PRESTAMO', COUNT(*) FROM PRESTAMO
UNION ALL SELECT 'DETALLE_PRESTAMO', COUNT(*) FROM DETALLE_PRESTAMO
UNION ALL SELECT 'MANTENIMIENTO', COUNT(*) FROM MANTENIMIENTO
UNION ALL SELECT 'MOVIMIENTO', COUNT(*) FROM MOVIMIENTO
UNION ALL SELECT 'NOTIFICACION', COUNT(*) FROM NOTIFICACION
UNION ALL SELECT 'AUDITORIA', COUNT(*) FROM AUDITORIA
ORDER BY tabla;

SELECT codigo, nombre, estado FROM ARTICULO WHERE estado = 'DISPONIBLE' ORDER BY codigo;
SELECT id_prestamo, fecha_prestamo, fecha_devolucion, estado FROM PRESTAMO WHERE estado = 'ACTIVO' ORDER BY fecha_devolucion;
SELECT id_auditoria, accion, fecha, id_usuario, tabla, descripcion FROM AUDITORIA ORDER BY fecha DESC;